const EXPENSE_TYPE = {
  DINE_OUT: 'DINE_OUT',
  GIFT: 'GIFT',
  GROCERY: 'GROCERY',
  HOUSE: 'HOUSE',
  MEMBERSHIP: 'MEMBERSHIP',
  OTHER: 'OTHER',
  TRANSPORTATION: 'TRANSPORTATION',
  TRAVEL: 'TRAVEL',
};

module.exports = {
  EXPENSE_TYPE,
};
