const MONEY_TYPE = {
  MONEY_IN_THE_BANK: 'MONEY_IN_THE_BANK',
  MONEY_INVESTED: 'MONEY_INVESTED',
  UNCLAIMED: 'UNCLAIMED',
  OTHER: 'OTHER',
  CHECKING: 'CHECKING',
  SAVINGS: 'SAVINGS',
  RRSP: 'RRSP',
  TFSA: 'TFSA',
  CASH: 'CASH',
  GIFT_CARD: 'GIFT_CARD',
};

module.exports = {
  MONEY_TYPE,
};
